variables:
    PROJECT_NAME: "PACECloudSDK"

stages:
    - test
    - build
    - publish

.android_version:
    tags:
        - android-latest

.testing:
    extends: .android_version
    stage: test
    only:
        - merge_requests

before_script:
    - export TAG_COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)
    - export BUILD_NUMBER=$(TZ=Etc/Utc date -j -f '%s' ${TAG_COMMIT_TIME} "+%Y%m%d%H")
    - export BUILD_VERSION_NAME=`echo $CI_COMMIT_TAG | cut -d '-' -f2`

code_style:
    extends: .testing
    script:
        - ./gradlew clean lint

unit_test:
    extends: .testing
    script:
        - ./gradlew clean library:testDebugUnitTest

android_test:
    extends: .testing
    before_script:
        - "/usr/local/share/android-sdk/tools/bin/sdkmanager 'system-images;android-28;google_apis;x86_64'"
        - "/usr/local/share/android-sdk/tools/bin/sdkmanager 'emulator'"
        - "echo no | /usr/local/share/android-sdk/tools/bin/avdmanager create avd --force --name api28 --package 'system-images;android-28;google_apis;x86_64' --abi 'x86_64' --device '5.4in FWVGA'"
        - "/usr/local/share/android-sdk/tools/emulator -avd api28 > /dev/null 2>&1 -skin 480x854 -no-audio -no-boot-anim -no-snapshot -memory 2048 &"
        - "/usr/local/share/android-sdk/platform-tools/adb wait-for-device"
    script:
        - ./gradlew clean library:connectedAndroidTest

library_review:
    extends: .android_version
    stage: build
    script:
        - ./gradlew clean library:assemble
    only:
        - merge_requests

documentation:
    extends: .android_version
    stage: build
    script:
        - ./gradlew clean dokkaHtml
        - zip -r android-pace-cloud-sdk-$BUILD_VERSION_NAME.zip library/build/dokka/*
    only:
        - tags
    artifacts:
        paths:
            - ./*.zip
        name: "android-pace-cloud-sdk-$BUILD_VERSION_NAME.zip"
        expire_in: 1 week

maven_central_upload:
    extends: .android_version
    stage: build
    script:
        - bash -c "echo '$SIGNING_GPG_KEY_CONTENT' | base64 -d > '$SIGNING_SECRET_KEY_RING_FILE'"
        - ./gradlew clean library:assembleRelease
        - ./gradlew sourcesJar javadocJar
        - ./gradlew publishReleasePublicationToMavenCentralRepository --max-workers 1 -PbuildNumber=$BUILD_NUMBER -PversionName=$BUILD_VERSION_NAME -PsigningKeyId=$SIGNING_KEY_ID -PsigningPassword=$SIGNING_PASSWORD -PsigningSecretKeyRingFile=$SIGNING_SECRET_KEY_RING_FILE -PossrhUsername=$OSSRH_USERNAME -PossrhPassword=$OSSRH_PASSWORD
    only:
        - tags

maven_central_close_and_release:
    extends: .android_version
    stage: publish
    script:
        - ./gradlew closeAndReleaseRepository -PossrhUsername=$OSSRH_USERNAME -PossrhPassword=$OSSRH_PASSWORD -PsonatypeStagingProfileId=$SONATYPE_STAGING_PROFILE_ID
    when: manual
    only:
        - tags

# GitHub Release
framework_publish_github:
    script:
        - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@${COMMON_REPO} tmp/common
        - pip3 install -r tmp/common/scripts/screenshots/requirements.txt
        - python3 tmp/common/scripts/tags/create_github_release.py -d pace/cloud-sdk-android
    allow_failure: true
    stage: publish
    only:
        - tags
    when: manual
